name: Deploy to dev/staging

on:
  pull_request:

  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: write-all

    name: Deploy to dev/staging

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3

      - uses: ./.github/workflows/yarn

      - uses: ./.github/workflows/build
        with:
          secrets: ${{ toJSON(secrets) }}
          is-production: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      # Deploy the main branch to staging
      - name: Deploy to the staging S3
        if: github.ref == 'refs/heads/main'
        env:
          BUCKET: s3://${{ secrets.AWS_STAGING_BUCKET_NAME }}/current
        run: bash ./scripts/github/s3_upload.sh

      # Deploy all other branches to dev
      - name: Deploy to the dev S3
        if: github.ref != 'refs/heads/main'
        env:
          BUCKET: s3://${{ secrets.AWS_DEVELOPMENT_BUCKET_NAME }}
        run: bash ./scripts/github/s3_upload.sh

      # Comment
      - name: Post a deployment link in the PR
        if: always() && github.event.number
        uses: mshick/add-pr-comment@v2
        with:
          message-id: praul
          message: |
            ## Branch preview
            ✅  Deployed to dev:

            https://safe-web-landing.dev.5afe.dev
          message-failure: |
            ## Branch preview
            ❌  Deploy failed!
